FROM jenkins/ssh-agent:latest-debian-jdk21

SHELL ["/bin/bash", "-e", "-u", "-o", "pipefail", "-c"]

USER root
# add docker lilst and gpg key to /etc/apt/keyrings/
RUN apt-get update -qq \
  && apt-get install -y curl ca-certificates \
  && mkdir -p /etc/apt/keyrings/ \
  && curl -fsSL https://download.docker.com/linux/debian/gpg > /etc/apt/keyrings/docker.asc \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
     https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
     > /etc/apt/sources.list.d/docker.list \
  && apt-get update -qq

RUN apt-get -y install docker-ce-cli
